"""empty message

Revision ID: 5716d0c98f50
Revises: a26b50c41494
Create Date: 2022-04-13 00:30:56.769437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5716d0c98f50'
down_revision = 'a26b50c41494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('fullName', sa.String(length=80), nullable=True))
    op.drop_column('users_table', 'lastName')
    op.drop_column('users_table', 'firstName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('firstName', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('users_table', sa.Column('lastName', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('users_table', 'fullName')
    # ### end Alembic commands ###
