"""empty message

Revision ID: a26b50c41494
Revises: 00d4536b7476
Create Date: 2022-04-12 21:53:17.579265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26b50c41494'
down_revision = '00d4536b7476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('make', sa.String(length=25), nullable=False),
    sa.Column('model', sa.String(length=25), nullable=False),
    sa.Column('colour', sa.String(length=25), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('transmission', sa.String(length=25), nullable=False),
    sa.Column('car_type', sa.String(length=25), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('photo', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favourites_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourites_table')
    op.drop_table('cars_table')
    # ### end Alembic commands ###
